---
params:
  EPOCHS: 1
  MOD: 1
  BATCH_SIZE: 2
  NUM_TRAIN: 10 # max 4254
  NUM_VAL: 5 # max 1700
  NUM_TEST: 5 # max 1700
addrs:
  TEST_ADDR: Test/*.npy
  TRAIN_ADDR: Train/*.npy
  VAL_ADDR: Val/*.npy
  MASK_ADDR: Inputs/mask.npy
  STATS_ADDR: Inputs/stats.npy
  IMMODEL_ADDR: Outputs/immodel
  REMODEL_ADDR: Outputs/remodel
  IMLOG_ADDR: Outputs/CompUNet.log
  RELOG_ADDR: Outputs/UNet.log
  FUNC_ADDR: Functions
  IMCHEC_ADDR: Outputs/imcheck
  RECHEC_ADDR: Outputs/recheck
  IMCSV_ADDR: Outputs/CompUNet_Train.log
  RECSV_ADDR: Outputs/UNet_Train.log
Hydra:
  run:
    dir: ./UofC2022/Outputs/CompUNet

