---
params:
  EPOCHS: 250 # 250 (WNet)
  MOD: 1.42 # 1.42: Modified to match ReUNet's trainable params roughly (+-1%) which isn't ideal
  RE_MOD: 1.0
  BATCH_SIZE: 16 # 16 (WNet)
  NUM_TRAIN: 4254 # max 4254
  NUM_VAL: 1700 # max 1700
  NUM_TEST: 1700 # max 1700
  NUM_MASKS: 100
  UNIT_CONFIRM: 2
  LR: 0.001
  ACCEL: 5
  BETA_1: 0.9
  BETA_2: 0.999
addrs:
  TEST: test/*.npy
  TRAIN: train/*.npy
  VAL: val/*.npy
  STATS: outputs_2/stats.npy
  COMP_MODEL: outputs_2/comp_model
  REAL_MODEL: outputs_2/real_model
  COMP_LOG: outputs_2/comp_unet.log
  REAL_LOG: outputs_2/unet.log
  FUNC: functions
  COMP_CHEC: outputs_2/comp_check
  REAL_CHEC: outputs_2/real_check
  COMP_CSV: outputs_2/comp_unet_train.log
  REAL_CSV: outputs_2/real_unet_train.log
  MASKS: inputs/masks_2/*.npy
  MASK_SAVE: inputs/masks_2
